import Head from 'next/head';
import Carousel from '../componants/Carousel';
import LatestPosts from '../componants/LatestPosts';
const url = process.env.NEXT_PUBLIC_BASE_URL;
export default function Home({ data }) {
	return (
		<div>
			<Head>
				<title>Blog name</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Carousel />
			<LatestPosts data={data} />
		</div>
	);
}
export async function getStaticProps() {
	const res = await fetch(`${url}/posts?per_page=3`);
	const data = await res.json();
	return {
		props: { data }, // will be passed to the page component as props
	};
}
